# Generated by Django 5.1.6 on 2025-03-21 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Review_Approval',
            fields=[
                ('Budget_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Budget_Department', models.CharField(max_length=100)),
                ('Budget_Amount_Requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Budget_Allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Budget_Justification', models.TextField()),
                ('Budget_Compliance_Status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('In Progress', 'In Progress')], default='In Progress', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Approval',
            fields=[
                ('Project_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=100)),
                ('Project_Objectives', models.TextField()),
                ('Project_Details', models.TextField()),
                ('Project_Timeline', models.CharField(max_length=100)),
                ('Project_Approval_Status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('In Progress', 'In Progress')], default='In Progress', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Monitoring',
            fields=[
                ('Project_Monitoring_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Project_Monitoring_Name', models.CharField(max_length=100)),
                ('Project_Monitoring_Objectives', models.TextField()),
                ('Project_Monitoring_Details', models.TextField()),
                ('Project_Monitoring_Status', models.CharField(choices=[('Active', 'Approved'), ('Terminated', 'Denied'), ('In Progress', 'In Progress')], default='In Progress', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasing_Approval',
            fields=[
                ('Purchase_Req_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Purchase_Vendor_Details', models.CharField(max_length=100)),
                ('Purchase_Item_Desc', models.TextField()),
                ('Purchase_Quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Purchase_Cost_Breakdown', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Purchase_Justification', models.TextField()),
                ('Purchase_Compliance_Status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('In Progress', 'In Progress')], default='In Progress', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Release_Approval',
            fields=[
                ('Employee_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Employee_Position', models.CharField(max_length=100)),
                ('Employee_Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Salary_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_Date', models.DateField()),
                ('Payroll_Summary', models.TextField()),
                ('salary_compliance_status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('In Progress', 'In Progress')], default='In Progress', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staffing_Approval',
            fields=[
                ('Staffing_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Staffing_Job_Role', models.CharField(max_length=100)),
                ('Staffing_Department', models.CharField(max_length=100)),
                ('Staffing_Request_Type', models.CharField(max_length=20)),
                ('Staffing_Leave_Duration', models.CharField(max_length=20)),
                ('Staffing_Reason_for_Leave', models.TextField()),
                ('Staffing_Status_Approval', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('In Progress', 'In Progress')], default='In Progress', max_length=30)),
                ('Staffing_Contract_Duration', models.CharField(max_length=20)),
            ],
        ),
    ]
